name: update-bot

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  check:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.fetcher.outputs.version }}
      tag: ${{ steps.fetcher.outputs.tag }}
    steps:
      - name: Fetch latest version
        id: fetcher
        run: |
          tag=$(curl -s ${GH_API} | jq -r '.[0].name')
          echo "version=${tag#v}" >> "${GITHUB_OUTPUT}"
          echo "tag=${tag}"       >> "${GITHUB_OUTPUT}"
        env:
          GH_API: https://api.github.com/repos/alist-org/alist/tags
  update:
    runs-on: ubuntu-latest
    needs: check
    steps:
      - uses: actions/checkout@v4.1.0
        with:
          fetch-depth: 0
      - name: Modify Dockerfile
        run: |
          sed -i "s/ARG VERSION=.*/ARG VERSION=${VERSION}/g" Dockerfile
        env:
          VERSION: ${{ needs.check.outputs.version }}
      - name: Setup git
        run: |
          git config user.name  "github-actions"
          git config user.email "github-actions@github.com"
      - name: Commit changes
        run: |
          if [ -z "$(git status --porcelain)" ]; then
            echo -e "✅ \033[32;1mNo changes to commit\033[1m"
          else
            git add    --all Dockerfile
            git commit --message "chore: bump version to ${TAG}"
            git tag    --annotate ${TAG} --message "${TAG}"
            git push   --follow-tags origin HEAD:${GITHUB_REF}
          fi
        env:
          TAG: ${{ needs.check.outputs.tag }}
