name: Release Container Image

on:
  push:
    tags: ["v*", "!v0.*"]
  workflow_dispatch:

permissions:
  packages: write
  contents: read

jobs:
  release:
    strategy:
      matrix:
        archs: ["amd64", "arm64", "s390x", "ppc64le"]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.0
      - name: Log in to Docker Hub
        uses: redhat-actions/podman-login@v1.6
        with:
          registry: docker.io
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
      - name: Log in to the GitHub Container Registry
        uses: redhat-actions/podman-login@v1.6
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Install qemu dependency
        run: |
          sudo apt-get update
          sudo apt-get install -y qemu-user-static
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5.0.0
        with:
          images: |
            docker.io/${{ secrets.DOCKER_USERNAME }}/alist
            ghcr.io/${{ github.actor }}/alist
          tags: |
            type=raw,value=latest,enable={{is_default_branch}}
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}
            type=sha
      - name: Build image with Buildah
        uses: redhat-actions/buildah-build@v2.12
        id: build-image
        with:
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          containerfiles: ./Dockerfile
          archs: ${{ matrix.archs }}
          layers: false
      - name: Push image to Container Registries
        uses: redhat-actions/push-to-registry@v2.7.1
        with:
          image: ${{ steps.build-image.outputs.image }}
          tags: ${{ steps.build-image.outputs.tags }}
