name: Build and Test Container

on:
  push:
    branches-ignore: [master]
  pull_request:
    branches: [master]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.0
      - uses: redhat-actions/buildah-build@v2.12
        with:
          containerfiles: ./Dockerfile
          tags: localhost/alist:latest
      - run: podman run --rm --pull never localhost/alist:latest --help
      - run: podman run --rm --pull never localhost/alist:latest version
      - run: |
          podman run -d --pull never --name alist localhost/alist:latest
          podman exec alist /usr/bin/alist --data /mnt/data admin random
          podman rm -f alist
